### ISSUE TITLE
Alt Gr + Klavo funkcias sole unue 

### ISSUE THREAD

**Issue by marie-bnl** [CapacitorSet/tajpi#1]
Se oni premtenas Alt Gr, kaj premas plurajn klavojn, la litero estas ĉapelita nur la unua fojo. Oni bezonas premi plurajn fojojn Alt Gr, por fari pli da ĉapelitajn literojn

**Comment by CapacitorSet** [comment]
Ĉi tiu projekto estas kopio de [tiu de Thomas James](http://www.zz9pza.net/tajpi/en/), bonvolu komuniki al li erarojn.

**Comment by marie-bnl** [comment]
Okej dankon!
